default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myapp
  password: password1
  host: localhost
  port: 5432

development:
  <<: *default
  database: educ-network_postgresql

test:
  <<: *default
  database: educ-network_test

production:
  <<: *default
  database: educ-network_prod
